defaults:
  - mppi: panda_push
  - isaacgym: push

goal: [0.5, 0.4, 0.7]
render: false
n_steps: 96
actors: ['panda_fe']
initial_actor_positions: [[0.0, 0.0, 0.8]]

nx: 14
cfg_root: '/input/mppi-isaac/conf/'
